Solve counterButton & VueCalculator
js-tasks-ru/vue-20220125_biryukov-gleb-98 pull request #2
Opened 2022-02-02 17:42 UTC by blackseliger

Здравствуйте, по поводу первой задачи, необходимо в самой vue затрагивать интерфейс event? currentTarget, target и т.д.?

2022-02-02 17:43 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-03 14:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-03 14:24 UTC, blackseliger commented
Можете сказать почему нельзя обработать исходный массив эмэйлов за границей компонента MarkedList?  https://github.com/blackseliger/vue-20220125_biryukov-gleb-98/blob/ad541238ec77ba7cc3dde33f75f6d17b187c7af7/01-basics/03-MarkedList/script.js#L33-L35
В итоге пришлось сделать так, это правильный подход? 
`  data() {
    return {
      emails: emails.map((item) => {
        return { email: item, search: false };
      }),`

Так же чем проблематичен подход если в шаблоне написать  `:class="marked: item.includes(this.search)"`  https://github.com/blackseliger/vue-20220125_biryukov-gleb-98/blob/ad541238ec77ba7cc3dde33f75f6d17b187c7af7/01-basics/03-MarkedList/index.html#L20

2022-02-03 16:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-03 16:50 UTC, blackseliger commented
Можете сказать пожалуйста, правильно ли подошел к использования опции watch и хорошо написан ли код тут? https://github.com/blackseliger/vue-20220125_biryukov-gleb-98/blob/7f0210a03b472d6da7268496a3c6bd5fb46cc949/01-basics/04-MeetupTitle/script.js#L32  В учебных заданиях редко работаю с fetch и promise, поэтому мало опыта с ними

2022-02-04 05:33 UTC, ShGKme requested changes
В 03-MarkedList требуется избавиться от побочных эффектов в вычисляемом свойстве.

2022-02-04 05:33 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Вычисляемые свойства при своём вычислении **ни в коем случае не должны иметь побочных эффектов, не должны изменять состояние, не должны изменять другие свойства**.

Это функции, которые возвращают значение, вычисленное на основе текущего состояния (других свойств), которое Vue сам присвоит в свойство компонента.

Мы не вызываем функцию сами, не контролируем её вызов. Мутация состояния в вычисляемом свойстве может привести к ошибкам и проблемам при отладке из-за неожиданного поведения, когда значения поменялись не тогда, когда ожидалось.

2022-02-04 05:33 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Текущее решение не просто вычисляет массив с маркировкой, а изменяет оригинальные данные `emails`. В итоге косвенно изменяется массив `this.emails` без явного указания на это.

Требуется в вычисляемом свойстве либо создавать копию массива (можно через `[...this.emails]` или `this.emails.slice()`), либо (лучше) использовать метод массива `map`.

2022-02-04 05:34 UTC, ShGKme commented
Сорри, посмотрел PR в срезе только одного коммита. Сейчас посмотрю остальные и вопросы.

2022-02-04 05:40 UTC, ShGKme requested changes
В 02-VueCalculator также проблема с побочными эффектами в вычисляемом свойстве. Остальные задачи приняты.

2022-02-04 05:40 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
>      </div>
У текстовой интерполяции принято добавлять пробелы: `{{ counter }}`

2022-02-04 05:40 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
>      </div>
Обычно принято использовать сокращённый вариант директив: `@click="..."`

2022-02-04 05:40 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
>      </div>
> по поводу первой задачи, необходимо в самой vue затрагивать интерфейс event? currentTarget, target и т.д.?

Нет, так как для увеличения значения достаточно `counter += 1`.

2022-02-04 05:40 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +    },
Аналогично предыдущему комментарию про вычисляемое свойство, при его вычислении ни в коем случае не должно быть побочных эффектов. Конкретно в этом решить проблему совсем просто. Свойство `this.result` не нужно. Оно нигде не используется в компоненте, кроме как "временная переменная" в вычисляемом свойстве. Его можно убрать и заменить на обычную локальную переменную (`let result = ...`) или ещё проще - сразу делать `return` с вычисленным значением в `case`-ах.

2022-02-04 05:40 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +    },
Проверка на неравенство не требуется. Такой ситуации никогда не будет, Vue не считает за изменение, если значение поменялось на точно такое же.

2022-02-04 05:43 UTC, ShGKme commented
> Можете сказать почему нельзя обработать исходный массив эмэйлов за границей компонента MarkedList?

Можно, но в коде по ссылке используется `map`. Он не меняет исходный массив, а возвращает новый. В вашем примере в закомментированном коде возвращаемое им значение нигде не использовалось.

> В итоге пришлось сделать так, это правильный подход?
data() { return { emails: emails.map((item) => { return { email: item, search: false }; }),

Именно в данной задаче - да, допустимый. Но, если бы `emails` мог изменяться (например, был бы входным параметром компонента или иным образом реактивным), лучше было бы сделать это в отдельном вычисляемом свойстве.

> Можете сказать пожалуйста, правильно ли подошел к использования опции watch и хорошо написан ли код тут? https://github.com/blackseliger/vue-20220125_biryukov-gleb-98/blob/7f0210a03b472d6da7268496a3c6bd5fb46cc949/01-basics/04-MeetupTitle/script.js#L32 В учебных заданиях редко работаю с fetch и promise, поэтому мало опыта с ними

Да, в части работы с fetch всё нормально. Название `titleID` лучше было поменять на `meetupTitle` или просто `title`, так как там хранится не `ID`, но это не относится к `fetch`, промисам или сути задачи.

2022-02-04 16:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-04 20:26 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-04 20:27 UTC, merged

2022-02-04 20:34 UTC, ShGKme commented
Не увидел, что была добавлена, но не решена новая задача...